name: Publish Website to Cpanel
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Cpanel
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.0"
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.production', '.env');"
      # - name: Install Dependencies
      #   run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      # - name: Update Dependencies
      #   run: composer update -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      # - name: Generate key
      #   run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd public_html/helpdesk.fmc.dufma.ng/estatevisa
            # composer update
            ea-php80 artisan key:generate
            ea-php80 artisan passport:install
            ea-php80 artisan migrate
